language: node_js
node_js:
  - "14"
  - "16"
  - "17"
matrix:
  fast_finish: true
script: "npm run-script test-ci"
before_install:
  - npm install -g typescript
after_script: 
  - "npm install coveralls@2.11.9 && cat ./coverage/lcov.info | coveralls"
